name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      env:
        GPWEBPAY_MERCHANT_PRIVATE_KEY: ${{secrets.GPWEBPAY_MERCHANT_PRIVATE_KEY}}
        GPWEBPAY_MERCHANT_PRIVATE_KEY_PASSPHRASE: ${{secrets.GPWEBPAY_MERCHANT_PRIVATE_KEY_PASSPHRASE}}

